CREATE TABLE IF NOT EXISTS users (
  userID INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  passwordHash VARCHAR(255) NOT NULL,
  role ENUM('Student','FacultyStaff','ResourceManager','Admin') NOT NULL DEFAULT 'Student',
  department VARCHAR(255),
  campusId VARCHAR(50),
  isActive BOOLEAN NOT NULL DEFAULT true,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS bookings (
  bookingID INT PRIMARY KEY AUTO_INCREMENT,
  userID INT NOT NULL,
  resourceID INT NOT NULL,
  startDateTime DATETIME NOT NULL,
  endDateTime DATETIME NOT NULL,
  status ENUM('Pending','Confirmed','Cancelled','Rejected','Completed') NOT NULL DEFAULT 'Pending',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userID) REFERENCES users(userID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS booking_approvals (
  approvalID INT PRIMARY KEY AUTO_INCREMENT,
  bookingID INT NOT NULL,
  approvedBy INT NOT NULL,
  approvalStatus ENUM('Approved','Rejected','Pending') NOT NULL DEFAULT 'Pending',
  remarks TEXT,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (bookingID) REFERENCES bookings(bookingID) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (approvedBy) REFERENCES users(userID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS blacklisted_tokens (
  id INT PRIMARY KEY AUTO_INCREMENT,
  tokenHash VARCHAR(64) NOT NULL UNIQUE,
  expiresAt DATETIME NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_tokenHash (tokenHash)
);

CREATE TABLE IF NOT EXISTS resources (
  resourceID INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  type VARCHAR(50) NOT NULL,
  location VARCHAR(255),
  capacity INT,
  status ENUM('Available','Maintenance','Inactive')
    DEFAULT 'Available',
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS bookingpolicy (
  policyID INT PRIMARY KEY AUTO_INCREMENT,
  maxAdvanceDays INT NOT NULL,
  minimumNotice VARCHAR(50) NOT NULL,
  maximumDuration VARCHAR(50) NOT NULL,
  cancellationDeadline VARCHAR(100) NOT NULL,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS policy_logs (
  logID INT PRIMARY KEY AUTO_INCREMENT,
  changedBy INT,
  description VARCHAR(255),
  changedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS archived_bookings (
  archiveID INT PRIMARY KEY AUTO_INCREMENT,
  originalBookingID INT,
  userID INT,
  userName VARCHAR(255),
  userEmail VARCHAR(255),
  resourceName VARCHAR(255),
  startDateTime DATETIME,
  endDateTime DATETIME,
  originalStatus VARCHAR(50),
  archivedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);